#pragma once

#define DETAIL_STRINGIFY(x) #x
#define DETAIL_EXPAND_AND_STRINGIFY(x) DETAIL_STRINGIFY(x)
#define DETAIL_CONCATENATE(a, b) a##b
#define KEY_HEADER_BY_SENDER_ID(id) DETAIL_EXPAND_AND_STRINGIFY(DETAIL_CONCATENATE(keys/event_keys_, id).hpp)

#include KEY_HEADER_BY_SENDER_ID(CONFIG_SENDER_ID)
